### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by tyx** [thephpleague/tactician-logger#8]
Hi guys,

Just notice we don't have a new tag since the last changes I made. Any chance to go up ?

**Comment by rosstuck** [comment]
Hey @tyx, sorry for the delay! I missed your answer on #7 (no emails for emoji responses) and then got caught up in conference stuff.

From my end, a new tag basically relies on #7. I'm currently on vacation right now but would like to address @boekkooi's concerns and maybe take one last peek at the interface before tagging an actual release (upon review, it's a bit obtuse and I had to orient myself again about the messages vs context part).

Again, sorry for the delay on this one, I'll make it a top priority foir next week when I'm back home again.

P.S. Will close this issue in favor of finishing discussion on #7 if that's okay.
